export const CREATE_USER_DATA = "ADD_USER_DATA";
export const CREATE_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const CREATE_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";